#
# ThingsBoard, Inc. ("COMPANY") CONFIDENTIAL
#
# Copyright © 2016-2025 ThingsBoard, Inc. All Rights Reserved.
#
# NOTICE: All information contained herein is, and remains
# the property of ThingsBoard, Inc. and its suppliers,
# if any.  The intellectual and technical concepts contained
# herein are proprietary to ThingsBoard, Inc.
# and its suppliers and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
#
# Dissemination of this information or reproduction of this material is strictly forbidden
# unless prior written permission is obtained from COMPANY.
#
# Access to the source code contained herein is hereby forbidden to anyone except current COMPANY employees,
# managers or contractors who have executed Confidentiality and Non-disclosure agreements
# explicitly covering such access.
#
# The copyright notice above does not evidence any actual or intended publication
# or disclosure  of  this source code, which includes
# information that is confidential and/or proprietary, and is a trade secret, of  COMPANY.
# ANY REPRODUCTION, MODIFICATION, DISTRIBUTION, PUBLIC  PERFORMANCE,
# OR PUBLIC DISPLAY OF OR THROUGH USE  OF THIS  SOURCE CODE  WITHOUT
# THE EXPRESS WRITTEN CONSENT OF COMPANY IS STRICTLY PROHIBITED,
# AND IN VIOLATION OF APPLICABLE LAWS AND INTERNATIONAL TREATIES.
# THE RECEIPT OR POSSESSION OF THIS SOURCE CODE AND/OR RELATED INFORMATION
# DOES NOT CONVEY OR IMPLY ANY RIGHTS TO REPRODUCE, DISCLOSE OR DISTRIBUTE ITS CONTENTS,
# OR TO MANUFACTURE, USE, OR SELL ANYTHING THAT IT  MAY DESCRIBE, IN WHOLE OR IN PART.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tbmq
  namespace: thingsboard-mqtt-broker
spec:
  serviceName: tbmq
  replicas: 2
  selector:
    matchLabels:
      app: tbmq
  template:
    metadata:
      labels:
        app: tbmq
    spec:
      volumes:
        - name: tbmq-config
          configMap:
            name: tbmq-config
            items:
              - key: conf
                path: thingsboard-mqtt-broker.conf
              - key: logback
                path: logback.xml
      containers:
        - name: server
          imagePullPolicy: Always
          image: thingsboard/tbmq-pe-node:2.2.0PE-SNAPSHOT
          ports:
            - containerPort: 8083
              name: http
            - containerPort: 1883
              name: mqtt-tcp
            - containerPort: 8883
              name: mqtt-ssl
            - containerPort: 8084
              name: mqtt-ws
          env:
            - name: TB_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TB_KAFKA_SERVERS
              value: "tbmq-kafka:9092"
            - name: HTTP_BIND_PORT
              value: "8083"
            - name: LISTENER_TCP_BIND_PORT
              value: "1883"
            - name: LISTENER_SSL_BIND_PORT
              value: "8883"
            - name: SECURITY_MQTT_BASIC_ENABLED
              value: "true"
            - name: STATS_ENABLED
              value: "true"
            - name: STATS_PRINT_INTERVAL_MS
              value: "10000"
            - name: METRICS_ENDPOINTS_EXPOSE
              value: "prometheus"
            - name: TB_KAFKA_ENABLE_TOPIC_DELETION
              value: "true"
            - name: TB_APP_PERSISTED_MSG_PACK_PROCESSING_TIMEOUT
              value: "15000"
            - name: REDIS_HOST
              value: "tbmq-valkey"
          envFrom:
            - configMapRef:
                name: tbmq-db-config
          volumeMounts:
            - mountPath: /config
              name: tbmq-config
          readinessProbe:
            tcpSocket:
              port: 1883
            timeoutSeconds: 10
            initialDelaySeconds: 30
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            timeoutSeconds: 10
            tcpSocket:
              port: 1883
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tbmq
  namespace: thingsboard-mqtt-broker
spec:
  type: NodePort
  selector:
    app: tbmq
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30001
      name: http
    - port: 1883
      targetPort: 1883
      nodePort: 30002
      name: mqtt-tcp
    - port: 8883
      targetPort: 8883
      nodePort: 30003
      name: mqtt-ssl
    - port: 8084
      targetPort: 8084
      nodePort: 30004
      name: mqtt-ws
